name: Code quality

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run Type Check
        run: yarn check-types

      - name: Run ESLint
        run: yarn check-lint

      - name: Run Tests
        run: yarn test --coverage
